[package]
name = "todo-plot"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
chrono-tz = "0.8.3"
clap = { version="4.2.2", features = ["derive"] }
rgb = "0.8.34"
textplots = "0.8.3"
